name: challenge 1

on: push

jobs:
    ubuntu1:
        name: First Job
        runs-on: ubuntu-latest
        steps:
        - name: print ubuntu date
          run: echo "$now"
    windows2:
        name: Second Job
        runs-on: windows-latest
        steps:
        - name: print windows date
          run: echo "12/5/2022"
    macos3:
        name: Third Job
        runs-on: macos-latest
        steps:
        - name: print mac date
          run: echo "todays date"
    other4:
        name: Fourth jobs
        runs-on: ubuntu-latest
        needs: [ubuntu1, windows2, macos3]
        steps:
        - name: print hello
          run: echo "hello"
         